### ISSUE TITLE
Past value.

### ISSUE THREAD

**Issue by spacecabbie** [iprak/yahoofinance#108]
Hi i am making an automation that basicaly calls out current price every 15 minutes on my home speakers.

Now I want to track the price like this: 
`service: tts.speak
target:
  entity_id: all
data:
  message: Current gold price is: {{states.sensor.yahoofinance_xaut_usd.state}} Last price was: {{states.sensor.yahoofinance_xaut_usd.?????}}
  media_player_entity_id: media_player.nest_speakers`

Any advice what i can do here ? I looked trough the list of states but none match price last x minutes orso

**Comment by iprak** [comment]
Sorry there is no such concept built into an entity. The previous data at market closing time is captured in `RegularMarketPreviousClose`.  You can save off the current value into a custom attribute after the announcement in the same automation.

Here are some articles which I found regarding updating custom attribute:
* https://community.home-assistant.io/t/how-to-change-an-attribute-of-an-entity-within-an-automation/491691/5
* https://community.home-assistant.io/t/change-attribute-value-via-automation/50999
