### ISSUE TITLE
list of names

### ISSUE THREAD

**Issue by lowieh** [iprak/yahoofinance#109]
Iam searching for the list from the crypto with cryptocurrency names which had to fill in the cryptoinfo.yaml
- platform: cryptoinfo
    id: ""
    cryptocurrency_name: "polkadot"
    currency_name: "eur"
    multiplier: 1
    update_frequency: 5

Second question is how do i delete the $ sign in de dashboard....the price of the crypto is the EUR price. 
![crypto usd](https://github.com/iprak/yahoofinance/assets/93491614/07c754af-67ce-407c-a29d-89d01f126cb7)

**Comment by iprak** [comment]
I don't follow your question. Is this question for cryptoinfo integration ?

**Comment by lowieh** [comment]
Hi, yes it is

Op vr 5 jan. 2024 17:54 schreef Indu Prakash ***@***.***>:

**Comment by iprak** [comment]
Then the question should be posted in https://github.com/heyajohnny/cryptoinfo
