### ISSUE TITLE
Pre-market, after-hours

### ISSUE THREAD

**Issue by christian1986** [iprak/yahoofinance#11]
Would it be possible to include these as well?

**Comment by iprak** [comment]
There is a data field named `postMarketPrice` which seems represent after hours value but I am not certain. There is no data field reflecting "pre-market" state.

**Comment by christian1986** [comment]
Nothing like preMarketPrice?

(Nice work btw😊)

**Comment by iprak** [comment]
I did not getting any data for `preMarketPrice` but am getting data for `regularMarketPreviousClose`. I will include `regularMarketPreviousClose, postMarketChange, postMarketChangePercent, postMarketPrice`.
