### ISSUE TITLE
DJI, SNP, NASDAQ displaying in USD should be integer 

### ISSUE THREAD

**Issue by FS1961** [iprak/yahoofinance#110]
How do I set this to give results in sensor only as integer instead of currency?

**Comment by iprak** [comment]
The values will be decimal, that matches values returned by Yahoo finance.

**Comment by iprak** [comment]
But you can force rounding using decimal_places (see Readme) for all symbols.

**Comment by FS1961** [comment]
Maybe I wasn’t clear. For instance, I have this Index (NASDAQ) which should report as volume not USD.  How can I lose the USD and just have it reported as a number? 

![IMG_1753](https://github.com/iprak/yahoofinance/assets/98458806/47ab0ad6-b6fe-4215-805d-32692e4dc023)

**Comment by iprak** [comment]
The entities have the `state_class` of [measurement](https://developers.home-assistant.io/docs/core/entity/sensor/) which goes along with a unit_of_measurement which is USD in this case. If the symbol represents conversion e.g. USDEUR=X, then the unit will be EUR. There is no option to remove this.

**Comment by FS1961** [comment]
Okay. I understand. It’s just that these are not dollar values like a normal stock - they are how many stocks are traded - volume. I will try and format this some how. Thanks! On Jan 25, 2024, at 1:04 PM, Indu Prakash ***@***.***> wrote:﻿
The entities have the state_class of measurement which goes along with a unit_of_measurement which is USD in this case. If the symbol represents conversion e.g. USDEUR=X, then the unit will be EUR. There is no option to remove this.

**Comment by iprak** [comment]
I did not know that. I will take a look at the data returned.. maybe something can be used to differentiate this or we could just use the fact that the symbol starts with ^.

**Comment by FS1961** [comment]
Thank you. On Jan 25, 2024, at 6:02 PM, Indu Prakash ***@***.***> wrote:﻿
I did not know that. I will take a look at the data returned.. maybe something can be used to differentiate this or we could just use the fact that the symbol starts with ^.

**Comment by iprak** [comment]
So when I look up an Index in YahooFinance, it shows with a currency which makes me think that these are calculated currency values. 
![image](https://github.com/iprak/yahoofinance/assets/6459774/b7dd7dbd-e1ec-460f-b47c-3b2ab6f01c35)

And since indices are based on different currency so currency should be included.
![image](https://github.com/iprak/yahoofinance/assets/6459774/d4153ec3-6395-4c0c-a1f4-44f8efa8c5cc)

And the data seems to be the similar for non-index symbols
![image](https://github.com/iprak/yahoofinance/assets/6459774/35023385-9fde-46d0-9676-bd6ed0b954c7)

**Comment by FS1961** [comment]
Yes and no.  Since these indices are based on US stock markets, they are “tied” to USD.

Here is a good example of how this works. https://www.investopedia.com/ask/answers/040215/what-does-sp-500-index-measure-and-how-it-calculated.asp

You may be correct that it can’t be removed but it’s not really USD. For example, the Dow Jones closed at 38,049.13 which is an index and not $38,049.13. it’s not a price. While AAPL (Apple) has a share price of $194.17.

If you can’t, I understand. I’ll try and format a variable to put in my dashboard.

Appreciate you taking the time to check this out.

Frank

**Comment by iprak** [comment]
See https://github.com/iprak/yahoofinance/releases/tag/v1.2.4

**Comment by FS1961** [comment]
Good morning,

I’ve loaded 1.2.4

Here is my config.yaml portion but I get an error when trying to restart HA:

yahoofinance:
  symbols:
    - ^GSPC
    - ^DJI
    - ^IXIC
  scan_interval:
    minutes: 1
  show_trending_icon: true
  unit_measure:
    no_unit: true
  decimal_places: 0

Can you show me where I need to put the params?

Thanks!

**Comment by iprak** [comment]
The setting is on the symbol definition itself, so it would be something like this
```
symbols:
  - symbol: ^GSPC
    no_unit: true
```

**Comment by FS1961** [comment]
Okay. I’ll give that a try. On Jan 27, 2024, at 2:39 PM, Indu Prakash ***@***.***> wrote:﻿
The setting is on the symbol definition itself, so it would be something like this
symbols:
  - symbol: ^GSPC
    no_unit: true

**Comment by FS1961** [comment]
Okay, works beautifully!

Thank you!

**Comment by FS1961** [comment]
Works perfectly!.

**Comment by FS1961** [comment]
Sorry, how do you set the scan interval to 5 minutes? Your example shows hours. Thanks! On Jan 27, 2024, at 8:37 PM, Frank Spatt ***@***.***> wrote:﻿Okay, works beautifully!Thank you!On Jan 27, 2024, at 2:39 PM, Indu Prakash ***@***.***> wrote:The setting is on the symbol definition itself, so it would be something like this
symbols:
  - symbol: ^GSPC
    no_unit: true

**Comment by iprak** [comment]
You can just do `scan_interval: 300` or 
```
scan_interval:
  minutes: 5
```

hours, minutes and seconds are the allows values for a period type value.

**Comment by iprak** [comment]
To help identify what is happening would want to enable debug logging.

This is from Developer Tools:
![image](https://github.com/iprak/yahoofinance/assets/6459774/2860f362-1bb6-4abe-884d-a5fac3c6a080)

Please submit a separate issue.
