### ISSUE TITLE
Timed out getting crumb. Source: custom_components/yahoofinance/coordinator.py:97

### ISSUE THREAD

**Issue by Johnyboy1984** [iprak/yahoofinance#115]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.yahoofinance.coordinator
Source: custom_components/yahoofinance/coordinator.py:97
Integration: Yahoo Finance (documentation, issues)
First occurred: 08:59:13 (1 occurrences)
Last logged: 08:59:13

Timed out getting crumb.

**Comment by iprak** [comment]
This seems to be for older version. No such exception is being raised at that line.
