### ISSUE TITLE
Yahoo Finance

### ISSUE THREAD

**Issue by Johnyboy1984** [iprak/yahoofinance#118]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.yahoofinance.coordinator
Source: custom_components/yahoofinance/coordinator.py:99
Integration: Yahoo Finance (documentation, issues)
First occurred: 20:23:33 (1 occurrences)
Last logged: 20:23:33

Timed out getting crumb.

**Comment by iprak** [comment]
Is this different from #115 ?

Going by the line number, it doesn't look like you have the latest release.

**Comment by iprak** [comment]
Can you provide an update on my  question?

**Comment by Johnyboy1984** [comment]
looking at the error code I would say yes. In one it is error code 99 and in the other it is error code 97

**Comment by iprak** [comment]
What is the integration version ?

**Comment by Johnyboy1984** [comment]
I currently have Yahoo version 1.2.6.
![image](https://github.com/iprak/yahoofinance/assets/96473114/fdd19ad9-cb35-4459-88e5-84eb84c989dd)

**Comment by iprak** [comment]
The code mentioned in the error was in an older version, maybe 1.2.4. Please update and see if the situation improves. Data fetch can fail and in that case the error is logged. I cannot do much about random failures itself but the integration will attempt a fetch again.
