### ISSUE TITLE
Dates for Dividends are in error

### ISSUE THREAD

**Issue by dustball62** [iprak/yahoofinance#119]
Hello - I tried to see where you are pulling the dates from for your dividend dates and I cant locate them. I'm considering setting up a HomeAssistant dedicated to Stocks and finance.  I would like to see if you can correct the dates for dividends, I have a few that I'm following as a test and the dates are incorrect.
for example:

"regularMarketPrice: 73.2
regularMarketVolume: 48096
regularMarketTime: 1708459934
**dividendDate: 2018-12-25**
fiftyDayAverage: 71.46
fiftyDayAverageChange: 1.74"

this is for USOI ticker symbol

also wonder if there are any plans to add Beta Yield or any of the other important metrics.

Thanks in advance

Dusty

**Comment by iprak** [comment]
Yahoo finance just provides a number for something termed as `dividendDate`. For USOI, the value is 1545782400 which sort of looks like an instant and that is what is provided. The data returned by the end point has no beta or yield metrics in it.

**Comment by dustball62** [comment]
thanks for looking into it
- you and I must be looking at different data on Yahoo!

![Screenshot 2024-02-20 173329](https://github.com/iprak/yahoofinance/assets/145878361/c39fd308-ea51-4a46-afc0-205fcbcbef77)

I appreciate your time,

Dusty

**Comment by iprak** [comment]
That is yahoo finance data but what the end point provides is a small subset of that data. This end point is not a public facing end-point. For USOI, that data is just this. This data varies by symbol as well. The `dividendDate` represents something but I frankly don't know what it is. 

```
'quoteType': 'ETF'
'typeDisp': 'ETF'
'quoteSourceName': 'Delayed Quote'
'triggerable': True
'customPriceAlertConfidence': 'HIGH'
'currency': 'USD'
'firstTradeDateMilliseconds': 1493213400000
'priceHint': 2
'postMarketChangePercent': -0.6261899
'postMarketTime': 1708477200
'postMarketPrice': 73.0
'postMarketChange': -0.45999908
'regularMarketChange': -0.27549744
'regularMarketTime': 1708462545
'regularMarketDayHigh': 73.92
'regularMarketDayRange': '73.04 - 73.92'
'regularMarketDayLow': 73.04
'regularMarketVolume': 49736
'regularMarketPreviousClose': 73.7355
'bid': 72.9
'ask': 73.49
'bidSize': 9
'askSize': 8
'fullExchangeName': 'NasdaqGM'
'regularMarketOpen': 73.92
'averageDailyVolume3Month': 50745
'averageDailyVolume10Day': 33670
'fiftyTwoWeekLowChange': 5.909996
'fiftyTwoWeekLowChangePercent': 0.087490685
'fiftyTwoWeekRange': '67.55 - 85.49'
'fiftyTwoWeekHighChange': -12.029999
'fiftyTwoWeekHighChangePercent': -0.1407182
'fiftyTwoWeekLow': 67.55
'fiftyTwoWeekHigh': 85.49
'fiftyTwoWeekChangePercent': -3.9918363
'dividendDate': 1545782400
'dividendYield': 24.82
'ytdReturn': 5.78583
'trailingThreeMonthReturns': -3.85857
'trailingThreeMonthNavReturns': -3.85857
'netAssets': 305608832.0
'fiftyDayAverage': 71.4592
'fiftyDayAverageChange': 2.000801
'fiftyDayAverageChangePercent': 0.02799921
'twoHundredDayAverage': 76.35395
'twoHundredDayAverageChange': -2.8939514
'twoHundredDayAverageChangePercent': -0.03790179
'netExpenseRatio': 0.85
'sourceInterval': 15
'exchangeDataDelayedBy': 0
'tradeable': False
'cryptoTradeable': False
'marketState': 'POSTPOST'
'regularMarketChangePercent': -0.37362933
'regularMarketPrice': 73.46
'exchange': 'NGM'
'shortName': 'Credit Suisse X-Links Crude Oil'
'longName': 'Credit Suisse X-Links Crude Oil Shares Covered Call ETNs'
'messageBoardId': 'finmb_429652484'
'exchangeTimezoneName': 'America/New_York'
'exchangeTimezoneShortName': 'EST'
'gmtOffSetMilliseconds': -18000000
'market': 'us_market'
'esgPopulated': False
'symbol': 'USOI'
```

**Comment by dustball62** [comment]
Thanks for your reply - i do see the timestamp on the dividenddate- as Epoch time Dec 26 2018- it must be an error on Yahoo's part.  I also see the data for yield beta alpha P/E ratio are also not present.  So i don't think this will be a good way to retrieve that information- thanks again for looking into it.
