### ISSUE TITLE
Include 200 days average and volume related stats

### ISSUE THREAD

**Issue by bhchew** [iprak/yahoofinance#12]
Might be useful to have both 50 and 200 days averages.

But not sure whether there's a real time volume available?

**Comment by iprak** [comment]
I will include `twoHundredDayAverage, twoHundredDayAverageChange, twoHundredDayAverageChangePercent, averageDailyVolume10Day, averageDailyVolume3Month, regularMarketVolume`. regularMarketVolume might be the real time volume.
