### ISSUE TITLE
Yahoo Finance Errors out with 'Header Value too Long'

### ISSUE THREAD

**Issue by mdframe** [iprak/yahoofinance#121]
I just started receiving the following error message with Yahoo Finance, which is a really cool add-in BTW:

2024-03-01 07:05:16.156 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Error accessing crumb url. 400, message='Got more than 8190 bytes (12793) when reading Header value is too long.', url=URL('https://finance.yahoo.com/quote/NQ=F')

I do not have any symbols with a 'F' in my list and this call is for a NASDAQ exchange update which I have not added anywhere.  What can I do to stop this call or stop this error?

I also added my 10th stock to track and it is not showing up.  Is there a limit to the number of stocks for tracking?

Thank you for this awesome add-in!

Matt

**Comment by iprak** [comment]
Quote for NASDAQ is initially fetched to establish a session. The header too long error usually auto resolves.

**Comment by iprak** [comment]
I have seen that header error but usually it happens the first time and then the integration recovers. I am not sure what exactly causes that long header but the underlying component aiohttp parsing the header is limited to 8190 characters ([here](https://github.com/rckclmbr/pyportify/issues/117)).

The NASDAQ symbol is used to establish access credentials.

No, there is no 10 symbol limit, I have like 23 symbols. I would check `Developer Tools > State` and `Settings > Devices & services > Entities` to see if they appear there.

**Comment by iprak** [comment]
The [1.2.7](https://github.com/iprak/yahoofinance/releases/tag/v1.2.7) release should have reduced incidents of this.

**Comment by iprak** [comment]
@mdframe Are you still seeing this after 1.2.7 ?
