### ISSUE TITLE
Use of asyncio.timeout 

### ISSUE THREAD

**Issue by ctaggmk** [iprak/yahoofinance#126]
Hi. Is this the same issue as #125? Apologies if it is! 

So new installation of yahoofinance via HACS so 1.26 as of today 16 Apr 2024

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/yahoofinance/coordinator.py:67
Integration: Yahoo Finance (documentation, issues)
First occurred: 17:47:04 (1 occurrences)
Last logged: 17:47:04

Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 274, in async_setup
    await _setup_coordinator()
  File "/config/custom_components/yahoofinance/__init__.py", line 225, in _setup_coordinator
    crumb = await crumb_coordinator.try_get_crumb_cookies()  # Get crumb first
  File "/config/custom_components/yahoofinance/coordinator.py", line 67, in try_get_crumb_cookies
    async with asyncio.timeout(WEBSESSION_TIMEOUT):
AttributeError: module 'asyncio' has no attribute 'timeout'

I did try just commenting out the offending line in coordinator.py but it bombs on another use of asyncio.timeout further down (line 322 if I remember rightly) so decided to park my hacking py file skills and log an issue instead.

**Comment by ctaggmk** [comment]
I noticed the WEBSESSION_TIMEOUT was set to 15 so edited the line and entered 15 directly. That has made no difference. It's like the version of asyncio it's using no longer has the .timeout attribute? But I can find relatively recent Google search results on it. Has it just been deprecated?

**Comment by ctaggmk** [comment]
Looking again at issue 125. I have no issue getting to Yahoo Finance from a browser and getting stock graphs is quick too

**Comment by iprak** [comment]
What is your HomeAssiatant version?

**Comment by iprak** [comment]
I strongly suspect that this is an older version of HomeAssistant, please update HomeAssistant.

**Comment by iprak** [comment]
Any update on this?

**Comment by iprak** [comment]
There has no response on this. This would have happened with older version of HomeAssistant.
