### ISSUE TITLE
SHIB-EUR value allways cero

### ISSUE THREAD

**Issue by txespirito** [iprak/yahoofinance#128]
The recovered value for SHIB-EUR is always 0.000000€ when for example it is now 0.000025€. I have no problems with the rest of the cryptocurrencies.
Thanks
<img width="417" alt="SHIB-EUR" src="https://github.com/iprak/yahoofinance/assets/65449504/e3601179-5aa7-41cc-8098-d9b4e38124f5">
<img width="366" alt="SHIB-EUR-2" src="https://github.com/iprak/yahoofinance/assets/65449504/e8110635-e190-4ee6-ac07-0a38fdde23a1">

**Comment by iprak** [comment]
Can you add an example (with values) of a symbol correctly showing?

**Comment by iprak** [comment]
By default, value is rounded to 2 places of decimal. You can use [decimal_places](https://github.com/iprak/yahoofinance) option to display values to more places of decimal.

**Comment by txespirito** [comment]
Decimals are not the problem.
Thanks
<img width="402" alt="Decimals" src="https://github.com/iprak/yahoofinance/assets/65449504/599fc4f1-ca9a-4ba7-a596-c642ccde9ec6">
<img width="406" alt="Cardano" src="https://github.com/iprak/yahoofinance/assets/65449504/2967bb0a-6183-4b1c-99bd-c28185539c82">

**Comment by txespirito** [comment]
Resolved. I only had to define 4 decimal places in the yaml configuration. Sorry for the oversight.
Thank you
