### ISSUE TITLE
get price/earnings ratio

### ISSUE THREAD

**Issue by Maximilian-Pichler** [iprak/yahoofinance#132]
Hey @iprak ,

First off, big thanks for the home assistant Yahoo Finance integration you made—it's pretty handy for tracking the market!

I was thinking, it would be super helpful to have Price/Earnings (P/E) ratios in there too. I reckon it could be great for making more informed decisions in our automations, like getting alerts when P/E goes beyond/below a certain target range.

I would create a pull-request, but i am not familiar with homeasssitant integrations.

Thanks again for the cool work on this

**Comment by iprak** [comment]
Are you referring to "PE Ratio (TTM)" ?

**Comment by Maximilian-Pichler** [comment]
yes, PE Ratio TTM is the backwards PE for 12 months.

**Comment by iprak** [comment]
I could only find 2 data elements: forwardPE and trailingPE related to that. I will add those. The yahoo end point only provides a limited set of data of what one might see at the website.

**Comment by Maximilian-Pichler** [comment]
that sounds great! thank you!

**Comment by iprak** [comment]
Addressed in 1.2.9
