### ISSUE TITLE
Problems to install 

### ISSUE THREAD

**Issue by SrekerGER** [iprak/yahoofinance#145]
Hi,

I tryed to install Yahoo Finance via HACS. After I copied the fils in the Configurationdirectory and edited the configuration.yaml and rebooted all,, th eintegration ist not working, i can not see any sensors. Here's the LOG:

Logger: homeassistant.config
Source: config.py:940
First occurred: 16:31:55 (1 occurrences)
Last logged: 16:31:55

Platform error: sensor - Integration 'yahoo_finance' not found.

can anybody help??

**Comment by SrekerGER** [comment]
![image](https://github.com/user-attachments/assets/9d604008-d514-47ec-974e-63d2858f7d69)
![image](https://github.com/user-attachments/assets/78b73ba8-a45b-41c1-bb4c-f996cbf1ebfb)
![image](https://github.com/user-attachments/assets/22bbe21f-8918-4c89-bea1-de87351f02b0)

These is what I see, aftrer I have installed it via HACS.
The directory is /homeassistant/custom_componants/yahoofinance (see screenshots)

As far as I know i do not have a "configuration directory", cause the configuration.ymal is in the directory "homassistant/"
I hope these information are helpful

Thanks for your help

**Comment by iprak** [comment]
Does your configuration have yahoo_finance instead of yahoofinance ?

**Comment by SrekerGER** [comment]
Hello,  I checked it and it is "yahoofinance".

**Comment by iprak** [comment]
The error message suggests otherwise - Platform error: sensor - Integration 'yahoo_finance' not found. Can you share your configuration?

**Comment by SrekerGER** [comment]
Hi, thanks for your hint. In the configuration.yaml was an error. I corrected it from "yahoo_finance" to "yahoofinance". Now I can see the custom integration in "Settings/Integrations". Thats a step foreward :-) 

BUT
I do not have any sensors. Here is my actual configuration for this part:
######
sensor:
  - platform: yahoofinance
    symbols:
      - AMZN  # Amazon
      - TSLA  # Tesla
      - NOK   # Nokia
      - NVDA  # Nvidia

######

I would expect to find a sensor like "sensor.yahoofinance_amzn", as described in the documatation.

Thanks for your help.

**Comment by iprak** [comment]
I would enable debug logging for the integration. The log might reveal what is happening.

**Comment by SrekerGER** [comment]
Hmm, I am not that familiar. How do I enable the logging for this integration?

**Comment by iprak** [comment]
There is an option under Integrations.![Screenshot_20241122-163806.png](https://github.com/user-attachments/assets/d4d9c0d9-641e-4cb7-a4be-333db7d3f28e)

**Comment by SrekerGER** [comment]
Hi, sorry this I could have find myself. Anyway, I enabled the debugging, but I can not find any entry in a log. I checkt every log i can find via the UI (settings/system/log). In the drop-down box, where all the logs are separated by integration, i can not see yahoofinance. (see screenshot)
![image](https://github.com/user-attachments/assets/071bacee-04c2-4fe3-a429-78b5392a2a08)

I have no idea where i can look elswhere.

**Comment by iprak** [comment]
Your configuration looks incorrect to me. The symbols node in yml should be indented. Please refer to the readme.

**Comment by SrekerGER** [comment]
Hi, thank you very much, this solved my problem. I guess I checkt the config to often, so i became somehow "blind" :-).

Maybe you finally can give me a hint how i can show the attributes on my dashboard?

Anyway, thanks again for solving my problem.
