### ISSUE TITLE
FEATURE REQUEST: IPOs Calendar

### ISSUE THREAD

**Issue by KutonnoZer0** [iprak/yahoofinance#16]
Could it be possible to have a notification for new IPOs calendar?
example:

```
sensor:
  - platform: yahoofinance
    calendar
```

and that could change to 1 for an update and after a few hrs change back to 0, that way we could create an alarm that could send a notification to the phone.

**Comment by iprak** [comment]
I am not sure I am following, can you provide more details and an example symbol.

**Comment by KutonnoZer0** [comment]
Hi, an example of the Calender is https://finance.yahoo.com/calendar/ipo in that example it will show you the new ipos that will be available between Dec 06,2020 to Dec 12,2020

**Comment by iprak** [comment]
Sorry, this just fetches data for defined symbols. The end point being used does not provide any such data
