### ISSUE TITLE
New request for configurable decimals

### ISSUE THREAD

**Issue by martusi61** [iprak/yahoofinance#17]
In fact, being able to enter the number of actions could be useful, but the possibility of managing the number of decimals would also simplify the output on the cards. Anyway thanks for the great job, this integration was missing in our Home Assistant.

**Comment by iprak** [comment]
Were you thinking of being able to define places_of_decimal for all numeric attributes or just the entity state?

**Comment by martusi61** [comment]
Both of them

**Comment by iprak** [comment]
I have addressed this in the latest release. The latest release is a breaking release needing change to component declaration.

**Comment by martusi61** [comment]
Great, many thanks.
