### ISSUE TITLE
UK stocks

### ISSUE THREAD

**Issue by domneedham** [iprak/yahoofinance#21]
How do we do UK stocks? Trying to get BT.A for example and nothing is returned.

**Comment by iprak** [comment]
[YahooFinance ](https://finance.yahoo.com/) does not seem to provide data for BT.A .

**Comment by iprak** [comment]
Any item listed in londonstockexchange don't appear in yahoo's data. Yahoo's data might be limited to items listed in US exchanges. I can't do anything about that.

**Comment by imist** [comment]
Yahoo provides data for many markets around the globe. Non-us stock symbols are suffixed with market and for London Stock Exchange this is .L and .IL.  So the symbol for BT GROUP PLC ORD for example is BT-A.L.

See this page for markets supported by Yahoo Finance: https://help.yahoo.com/kb/SLN2310.html

**Comment by iprak** [comment]
Good to know. I will add this to the wiki.
