### ISSUE TITLE
MINIMUM_SCAN_INTERVAL

### ISSUE THREAD

**Issue by gerryhsu38** [iprak/yahoofinance#24]
I was setup scan_interval as 1sec, after update seems like minimum_scan_interval is change to 30sec. suggestion keep minimum scan interval as 1sec thanks

**Comment by iprak** [comment]
Refresh per second is excessive in terms of free use of an end point. I want the keep the chances of this end point disappearing due to misuse. In comparison, Alpha Vantage allows 5 free queries per minute.
