### ISSUE TITLE
Trending up color green, trending down red Feature request

### ISSUE THREAD

**Issue by chris669** [iprak/yahoofinance#25]
All is in the title, when up arrow should be green and when down should be red.
Thanks!

**Comment by iprak** [comment]
Icons are monotonic; you can add colors by customization in the card. There are many ways to achieve this and I personally use this appraoch (https://github.com/iprak/yahoofinance/issues/14#issuecomment-743485687).

**Comment by chris669** [comment]
OK, I thought it was like light on (yellow) , light off. Will try that, thanks
