### ISSUE TITLE
Feature request - set a currency for currency conversion

### ISSUE THREAD

**Issue by reinerr16** [iprak/yahoofinance#27]
Hello,

I would like to have the value delivered back in a different currency than yahoo. I also track prices of ETFs such as the following: https://finance.yahoo.com/quote/EMIM.L
This one is listed in GPB. Would it be possible to include an automatic conversion for this, so that the price is displayed in the specified currency.
The rates of GBP => USD => EUR are provided by Yahoo Finance(GBPUSD=X / EURUSD=X), but I don't want to miss out on all attributes and features with a custom template sensor.

Regards

**Comment by iprak** [comment]
Yes that should be possible. I am thinking that an enhancement to the declaration like this can indicate currency translation.

```yaml
yahoofinance:
  symbols:
    - symbol: EMIM.L
      target_currency: EUR
```

**Comment by reinerr16** [comment]
this would be really great and an easy option for international users!
