### ISSUE TITLE
Errors when starting home assistant

### ISSUE THREAD

**Issue by ReenigneArcher** [iprak/yahoofinance#44]
I get the following errors when starting home assistant
![image](https://user-images.githubusercontent.com/42013603/118280267-07937680-b49a-11eb-8c5a-3c2adc49ee98.png)

```
Logger: homeassistant.setup
Source: custom_components/yahoofinance/__init__.py:116
First occurred: 9:22:10 AM (1 occurrences)
Last logged: 9:22:10 AM

Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 148, in async_setup
    scan_interval = parse_scan_interval(domain_config.get(CONF_SCAN_INTERVAL))
  File "/config/custom_components/yahoofinance/__init__.py", line 116, in parse_scan_interval
    elif scan_interval < MINIMUM_SCAN_INTERVAL:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'
```

```
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 9:22:10 AM (1 occurrences)
Last logged: 9:22:10 AM

Unable to prepare setup for platform yahoofinance.sensor: Unable to set up component.
```

This is the relevant part of my configuration.yaml
```
#sensors
sensor: !include_dir_merge_list include_files/sensor/
```

And inside that directory a file named yahoofinance.yaml
```
#yahoofinance
- platform: yahoofinance
  show_trending_icon: true
  scan_interval:
    minutes: 15
  symbols:
    - AMD
    - ALGT
    - AMZN
```

**Comment by iprak** [comment]
You must have upgraded yahoofinance, it has to be defined as a component and not under sensor. This was changed in v1.0.0 ([Breaking Changes](https://github.com/iprak/yahoofinance)).

**Comment by ReenigneArcher** [comment]
I read that and didn't catch what was different, but got it working now by doing this in my config.

```
yahoofinance: !include include_files/components/yahoofinance.yaml
```

And this in my yahoofinance.yaml
```
#yahoofinance
show_trending_icon: true
scan_interval:
  minutes: 15
symbols:
  - AMD
  - ALGT
  - AMZN
```

Whenever possible I try to keep the main config as simplified as possible. Do you know if there is a way I can use the `!include_dir_merge_list` method and just automatically include all the component yaml files in that directory?

**Comment by iprak** [comment]
I use [packages ](https://www.home-assistant.io/docs/configuration/packages/)based layout and the `packages` folder has a yaml for yahoofinance.
```
packages: !include_dir_named packages
```

I am sure there are other ways to organize configuration.

**Comment by ReenigneArcher** [comment]
Thank you! Learned something new today!
