### ISSUE TITLE
Errors and inaccurate data when changing or adding config symbols

### ISSUE THREAD

**Issue by Leinad1904** [iprak/yahoofinance#49]
When adding or replacing symbols to the original config, I end up getting errors in the Home Assistant log, like this:

`2021-05-27 18:04:44 WARNING (MainThread) [custom_components.yahoofinance.coordinator] Requested data for SPDR and received MSFT`

When this occurs, inaccurate data is represented in lovelace (SPDR populated with MSFT values, and MSFT values are null):

![snip_1](https://user-images.githubusercontent.com/65045480/119908408-1f4a1080-bf18-11eb-9ac2-fbb4c00609ca.PNG)
![SPDR_Entity](https://user-images.githubusercontent.com/65045480/119908406-1f4a1080-bf18-11eb-950c-3feda8d10e7c.PNG)
![MSFT_Entity](https://user-images.githubusercontent.com/65045480/119908407-1f4a1080-bf18-11eb-93b3-32e54cd4990a.PNG)

**Comment by iprak** [comment]
Can you include your configuration for Yahoo finance sensors? Also what do you mean by "When adding or replacing symbols to the original config,"?

**Comment by iprak** [comment]
I have made some improvements based on what I thought might have happened. In future, please do add the configuration when logging an issue.
