### ISSUE TITLE
UI-integration an new attributes

### ISSUE THREAD

**Issue by Tom-ahawk** [iprak/yahoofinance#54]
Please consider the following functionality:

1. Make an UI-integration so stocks can be added using the UI. – No restart off HA needed.

2. Add two attributes, «buy price» and «number of stocks»
Using the UI-integration the two attributes can be set by the user.

This way a portfolio can be created in HA for daily monitoring.

Cheers.

UPDATE: 
I see the functionality #2 has been proposed before. I am a N00b, where and how, in your code do I write in some code to get two new attributes? This way I can populate them manually.

**Comment by iprak** [comment]
I do not have any plans on introducing UI-integration or incorporating buying details.
