### ISSUE TITLE
[Feature Request] Portfolio Holdings

### ISSUE THREAD

**Issue by MrBlue90** [iprak/yahoofinance#69]
Hi,

Thanks for creating this project.
Any chance it would be possible to add the portfolio holdings (total $$$) including total/day gains/losses?

Cheers

**Comment by iprak** [comment]
Sorry this does not do portfolio management, there are too many inputs involved. The same was requested in #15 but there are many more cases. You can create template sensors to do that or use custom appDaemon app (see #15).

**Comment by rubdos** [comment]
@iprak sorry to comment on a closed issue, but did you think about using Yahoo's portfolio tracking functionality? I'm not sure whether it has an API, but if it does, that would considerably lessen the maintenance of such a feature.
