### ISSUE TITLE
Wrong unit / currency for symbol

### ISSUE THREAD

**Issue by wernerhp** [iprak/yahoofinance#9]
I've added `BABA` (Alibaba Group Holding Limited), which is supposed to be in `USD`, however it's pulled into HA as `CNY`
![image](https://user-images.githubusercontent.com/2578772/100539111-b28ddc00-323c-11eb-8688-1631f025ed6b.png)

![image](https://user-images.githubusercontent.com/2578772/100539118-c76a6f80-323c-11eb-8524-bc0a4e221c22.png)

**Comment by AlexandreLogist** [comment]
Hi,

Having the same issue for another stock... Being pulled as USD in HA, but it's EUR on Yahoo.
Any config change to do ? Tried in the const file, but not getting it working :) 

KR

**Comment by iprak** [comment]
Which symbol?
