### ISSUE TITLE
not registering as integration

### ISSUE THREAD

**Issue by fmonday** [iprak/yahoofinance#90]
Yahoofinance is not following core HA guidelines for registering as integration, which means that there's no entry in 
`config/.storage/core.config_entries`. 

As such it can't be identified by `entry_id` which is needed by services like `homeassistant.reload_config_entry`.

**Comment by iprak** [comment]
I am not sure what you are referring to but yes this component does not appear under Integrations.

**Comment by iprak** [comment]
This seems to be the same as https://github.com/iprak/yahoofinance/issues/54, closing it as duplicate.
