### ISSUE TITLE
Scan interval none not working

### ISSUE THREAD

**Issue by smartypantsuk** [iprak/yahoofinance#92]
Hi, 

My configuration fails with this error if I use None or none for scan_interval

Invalid config for [yahoofinance]: expected float for dictionary value @ data['yahoofinance']['scan_interval']['hours']. Got 'none'. (See /config/configuration.yaml, line 25).

Configuration:
yahoofinance:
      scan_interval:
           hours: None
      symbols:
           - AMAZ

Sorry I don't know how to format for indent on here. 
Thanks

**Comment by iprak** [comment]
What are you trying to do by setting `hours: None` ?

**Comment by smartypantsuk** [comment]
I was trying to disable scanning so that I could run it via a more detailed schedule using an automation.

**Comment by iprak** [comment]
Sorry that is not possible right now. `hours: None` makes the scan_interval validation fail. You can perhaps define a large scan interval and then update as necessary.

**Comment by smartypantsuk** [comment]
Yes I'll do that,  thanks. 
What is the maximum scan_interval?

**Comment by iprak** [comment]
There is no max limit .. maybe you could use `hours` or `weeks`. Sorry I haven't really tested the fetch at such delayed intervals, the focus is usually on shorted durations. But the fetch is however happening via HomeAssistant DataCoordinator so I am quite confident that it should work. 

Can you explain your automation based workflow more? Are you trying to avoid data points in the graph?

**Comment by Trago5** [comment]
Using `scan_interval: None` works for me.
