### ISSUE TITLE
Invalid Crumb

### ISSUE THREAD

**Issue by hansbruy** [iprak/yahoofinance#93]
Since somewhere this afternoon getting error messages 

`2023-04-19 20:55:00.293 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Received status 401 for https://query1.finance.yahoo.com/v7/finance/quote?symbols=BATS.L,LGEN.L,PHNX.L,RIO.L,HSBA.L,WINK.L,AGNC,GOOD,ICMB,MO,NMFC,ORCC,F*GC.CMX
2023-04-19 20:55:00.293 WARNING (MainThread) [custom_components.yahoofinance.coordinator] Error obtaining data, retrying in 20 seconds.
'

When doing the call via browser response is: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}

Running on version 1.1.11

Any idea how to resolve?

Best regards,
Hans

**Comment by oli737** [comment]
No, but I have same problem.

2023-04-19 21:19:00.158 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Received status 401 for https://query1.finance.yahoo.com/v7/finance/quote?symbols=VWCE.DE,VWRL.AS,EUNL.DE,MSF.SG,EOAN.HA,NQSE.DE,SRT.DE,PAH3.SG,ASMF.F,IUSQ.DE,IUSN.DE,CCC3.F,22UA.F,18FX.DE,GOOG,BRK-B,AMZN,VHYL.AS,MDO.F,NFC.F,L0CK.DE,SGMR.F,CSSPX.MI,7MR.F,HAL.DE,PAE.F,PFE.F,JBL.SG,OPC.SG,IE00BNG8L278.SG
2023-04-19 21:19:00.161 WARNING (MainThread) [custom_components.yahoofinance.coordinator] Error obtaining data, retrying in 20 seconds.

**Comment by iprak** [comment]
Something seems to have changed at Yahoo end. Maybe they the request now needs a crumb to prevent undocumented access like from this component. 

Seems this limitation is only with v7 of the end point. So switching to v6 might work as a temporary measure.

**Comment by traveler2100** [comment]
It seems it is either down or changed as iprak said, it is down in my Excel add in as well.  Very frustrating.

**Comment by z06Drew** [comment]
Getting the same error over here also, just started today.

**Comment by hansbruy** [comment]
> It seems it is either down or changed as iprak said, it is down in my Excel add in as well. Very frustrating.

Yep - correct.
I also have an excel-sheet that collects data using v7, v8 and v11 calls and the v7 calls are not getting response back while v8 and v11 are retrieving the data as expected.

Guess we'll have to wait for yahoo to pick up and either correct the issue at hand or reverse the changes they made (if any)

**Comment by oli737** [comment]
It was working on off during the day. Now it's fully down for me.

**Comment by z06Drew** [comment]
Is there a way we can override the default URL through config to use v6?

**Comment by iprak** [comment]
@z06Drew Right now there is no configuration for this. I think I would want to try v7 and then fall back to v6 .. I am hoping that Yahoo reverses the change.  You can edit the file `custom_components/yahoofinance/const.py`, change v7 to v6 there and retsart HA.

**Comment by z06Drew** [comment]
@iprak  I updated the base URL in the const.py file to v6 and it worked for about 10 minutes, but not I'm getting the same error sporadically.

**Comment by iprak** [comment]
I wouldn't be surprised. The change at Yahoo end could be propagating to other versions of the end point.

**Comment by kalavo** [comment]
v6 working fine here

**Comment by lbonherbe** [comment]
Can you please share the changes you do in const.py to make it work again? What is the v6 URL?

**Comment by Hafinator** [comment]
@lbonherbe  just change the "v7" in the URL to "v6" that is it :)

**Comment by iprak** [comment]
I have addressed some aspect of this in [v1.2.1](https://github.com/iprak/yahoofinance/releases/tag/v1.2.1).

**Comment by dougle03** [comment]
> I have addressed some aspect of this in [v1.2.1](https://github.com/iprak/yahoofinance/releases/tag/v1.2.1).

Just tried, still no joy.

**Comment by iprak** [comment]
> > I have addressed some aspect of this in [v1.2.1](https://github.com/iprak/yahoofinance/releases/tag/v1.2.1).
> 
> Just tried, still no joy.

Please add the debug log.

**Comment by dougle03** [comment]
> Please add the debug log.

Can you give me a clue where that is? Sorry, new to this...

**Comment by dougle03** [comment]
> Please add the debug log.

This error originated from a custom integration.

Logger: custom_components.yahoofinance.coordinator
Source: custom_components/yahoofinance/coordinator.py:307
Integration: Yahoo Finance (documentation, issues)
First occurred: 13:05:38 (31 occurrences)
Last logged: 13:15:37

Received status 401 (error=Unauthorized) for https://query1.finance.yahoo.com/v7/finance/quote?symbols=RR.L,BT-A.L,ARB.L

**Comment by iprak** [comment]
> > Please add the debug log.
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.yahoofinance.coordinator Source: custom_components/yahoofinance/coordinator.py:307 Integration: Yahoo Finance (documentation, issues) First occurred: 13:05:38 (31 occurrences) Last logged: 13:15:37
> 
> Received status 401 (error=Unauthorized) for https://query1.finance.yahoo.com/v7/finance/quote?symbols=RR.L,BT-A.L,ARB.L

Can you enable debug logging and attach all the log for YahooFinance ?

https://www.home-assistant.io/integrations/logger/

```
logger:
  default: warn
  logs:
    custom_components.yahoofinance: debug
```

**Comment by iprak** [comment]
The initial request to _custom_components.yahoofinance.coordinator_ Getting crumb from from https://finance.yahoo.com/quote/NQ%3DF _ does not seem to be returning meaningful data. I am not seeing that but will try from some other machine.

**Comment by swiergot** [comment]
Still not working for me, even with 1.2.1.

```
2023-04-20 14:40:16.148 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Received status 401 (error=Unauthorized) for https://query1.finance.yahoo.com/v7/finance/quote?symbols=MSI,^GSPC,USDPLN=X,EURPLN=X,CHFPLN=X,EURUSD=X,VUSA.AS
2023-04-20 14:40:16.151 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Error fetching YahooSymbolUpdateCoordinator data: No data received
2023-04-20 14:40:16.540 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Received status 401 (error=Unauthorized) for https://query1.finance.yahoo.com/v7/finance/quote?symbols=MSI,^GSPC,USDPLN=X,EURPLN=X,CHFPLN=X,EURUSD=X,VUSA.AS
2023-04-20 14:40:16.559 WARNING (MainThread) [custom_components.yahoofinance.coordinator] Error obtaining data, retrying in 20 seconds.
```

**Comment by dougle03** [comment]
@iprak All working for me now. It just started working again. Thanks for taking the time to look into it. 👍

**Comment by swiergot** [comment]
Same here, started on its own after some time. Thanks!

**Comment by hansbruy** [comment]
Closing the issue as situation seems to be back to normal
@iprak : thanks for the very fast response

**Comment by thyeestes** [comment]
I have version 1.2.1 installed but still get the unauthorized errors, tried reloading the component but without success. 

Any ideas?

**Comment by swiergot** [comment]
> I have version 1.2.1 installed but still get the unauthorized errors, tried reloading the component but without success.
> 
> Any ideas?

Upgrade to 1.2.2 and restart HA.

**Comment by thyeestes** [comment]
Thanks working again
