### ISSUE TITLE
yahoo financed down?

### ISSUE THREAD

**Issue by jpoeppelman1** [iprak/yahoofinance#94]
Today I started to see this error message, it's happening for all queries.

{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}

**Comment by Sharknoon** [comment]
Same here `Received status 401 for https://query1.finance.yahoo.com/v7/finance/quote?symbols=DTG.DE,P911.DE`

**Comment by jpoeppelman1** [comment]
is an API key required and does it need to be refreshed?

**Comment by iprak** [comment]
There is no API key. This is a duplicate of https://github.com/iprak/yahoofinance/issues/93.
